server:
  port: 8730
spring:
  application:
    name: zuulServer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
#zuul:
#  routes:
#    client:
#      path: /myclient/**
#      serviceId: eurekaClientHello
eurekaClientHello.ribbon.NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
#配置zipKin Server的地址
#spring.zipkin.base-url: http://localhost:9411